### ISSUE TITLE
how to revalidate ssg pages; generated types does not offer this option

### ISSUE THREAD

**Issue by sushilbansal** [correttojs/graphql-codegen-apollo-next-ssr#11]
in getStaticProps one can return 
````
return {
    props: {
      apolloState: apolloClient.cache.extract(),
    },
    revalidate: 1,
  }
````
but the generated types through this bundle does not provide this option to revalidate the pages

**Comment by sushilbansal** [comment]
found a workaround. do not return the default return. Add it to revalidate before returning it to the page

**Comment by correttojs** [comment]
You can add any property you need before returning getStaticProps or getServerSideProps
