### ISSUE TITLE
TS option strict: true

### ISSUE THREAD

**Issue by mononoke-choi** [correttojs/graphql-codegen-apollo-next-ssr#13]
is it possible to use with Typescript compiler option 'strict: true' ?
it seems to be a little problem about 'optionsFunc' parameter which might be undefined value.
thank you for your work!
![image](https://user-images.githubusercontent.com/44839313/91022505-46458000-e630-11ea-87ff-5956fb8cbe9a.png)

**Comment by correttojs** [comment]
thank you for the feedback, it should work now
