### ISSUE TITLE
Make Apollo state key configurable

### ISSUE THREAD

**Issue by tmm** [correttojs/graphql-codegen-apollo-next-ssr#146]
I set up my Apollo client using the [Next.js Apollo example](https://github.com/vercel/next.js/blob/canary/examples/with-apollo/lib/apolloClient.js#L7) so my state is stored using the key `__APOLLO_STATE__` instead of `apolloState`.

https://github.com/correttojs/graphql-codegen-apollo-next-ssr/blob/536ca605c09396e6229c1f664fc9a09ad15787e7/src/visitor.ts#L202-L206

It would be great if this could be configurable. Maybe something like the following for backwards compatibility:

`apolloStateKey` (default: 'apolloState'): Key used for storing Apollo state

If this sounds good, I'm happy to create a PR.

**Comment by correttojs** [comment]
hi @tmm, thanks for the feedback. Sure, feel free to open the PR!

**Comment by tmm** [comment]
@correttojs opened #147
