### ISSUE TITLE
Respecting `importDocumentNodeExternallyFrom: near-operation-file`

### ISSUE THREAD

**Issue by Pikachews** [correttojs/graphql-codegen-apollo-next-ssr#15]
According to the documentation in `graphql-code-generator` (https://graphql-code-generator.com/docs/plugins/typescript-apollo-next#importdocumentnodeexternallyfrom`, setting 
```
documentMode: external
importDocumentNodeExternallyFrom: near-operation-file
```
should properly import document nodes from the files created using the `near-operation-file` preset, but according to the source code and the output I'm getting, that doesn't seem to be the case. Instead, it tries to directly import
```
import * as Operations from "near-operation-file";
```

Would it be possible to fix this behavior? Thanks!

**Comment by Pikachews** [comment]
Sorry, looks like I was fundamentally misunderstanding how to use the `near-operation-file` preset, not due to this plugin!

**Comment by mmahalwy** [comment]
@Pikachews can you explain more? I have the same problem too.
