### ISSUE TITLE
Example conf?

### ISSUE THREAD

**Issue by KATT** [correttojs/graphql-codegen-apollo-next-ssr#17]
Hey!

I'm struggling a bit on how to use this. See my PR on my play-project here: [`KATT/e2e-typesafety/pull/1`]()https://github.com/KATT/e2e-typesafety/pull/1

In my generated file it refers to an `Operations` object that I don't know where it comes from: [`KATT/e2e-typesafety/blob/feature/graphql-codegen-apollo-next-ssr/apollo/__generated__/graphql.tsx#L56`](https://github.com/KATT/e2e-typesafety/blob/feature/graphql-codegen-apollo-next-ssr/apollo/__generated__/graphql.tsx#L56)

You can see my config here: [`ssr/codegen.js`](https://github.com/KATT/e2e-typesafety/blob/feature/graphql-codegen-apollo-next-ssr/codegen.js#L15)

What am I missing to get it live and kicking?

Thanks

**Comment by KATT** [comment]
Got the generation working finally, thanks

**Comment by marcebdev** [comment]
> Got the generation working finally, thanks anyway! 🙏

Could you by any chance specify what fixed this for you? Been starring at this error for multiple hours now with a teammate going in circles where we either hit this error, a codegen error not regarding this plugin, or some combination

**Comment by KATT** [comment]
No idea, don't remember doing this haha

**Comment by correttojs** [comment]
can you share your `codegen.yml` ?
you can also considering using the [Typed Document Node](https://github.com/dotansimha/graphql-typed-document-node) so you can implement your own `getServerSideProps` typesafe interface
