### ISSUE TITLE
Provided example not working

### ISSUE THREAD

**Issue by dmaisano** [correttojs/graphql-codegen-apollo-next-ssr#192]
I tried running the example project included in the repo and ran into some errors, see below. As is provided out of the box from the repo, I could not get it to run. Not sure if anyone else has encountered the same issue as me.

[console output (gist)](https://gist.github.com/dmaisano/9b7da0f4dfe867c2779172657564c542)

![image](https://user-images.githubusercontent.com/17837521/121109195-13443580-c7d9-11eb-8044-38e960bd3ff1.png)

**Comment by WillSquire** [comment]
Did the same thing. Need to replace `./build/src/index.js` with `graphql-codegen-apollo-next-ssr`. Documentation is incoherent

**Comment by RileySeaburg** [comment]
> Did the same thing. Need to replace `./build/src/index.js` with `graphql-codegen-apollo-next-ssr`. Documentation is incoherent

That seemed too obvious but hey that's showbiz.

**Comment by correttojs** [comment]
the example uses a relative path `./build/src/index.js` so it can be tested before releasing a new version.
Please use `graphql-codegen-apollo-next-ssr` on your project
