### ISSUE TITLE
Use `NextPage` for PageComp type instead of `React.FC`

### ISSUE THREAD

**Issue by rohit-gohri** [correttojs/graphql-codegen-apollo-next-ssr#293]
Currently Page Component types get generated using `React.FC` but it should be using `NextPage`

Current:
```tsx
import type React from 'react';

export type PageAllOrdersComp = React.FC<{data?: AllOrdersQuery, error?: Apollo.ApolloError}>;
```

Expected
```tsx
import type { NextPage } from 'next';

export type PageAllOrdersComp = NextPage<{data?: AllOrdersQuery, error?: Apollo.ApolloError}>;
```

**Comment by alete89** [comment]
is there any substancial difference between `NextPage` and `React.FC` ?

**Comment by rohit-gohri** [comment]
There was some usecase related to inference and `InferProps` not working without the type being based on `NextPage`. But I don't remember the specifics now. I'll close this
