### ISSUE TITLE
Unusable when query name has `Page` or `Query`

### ISSUE THREAD

**Issue by hinsxd** [correttojs/graphql-codegen-apollo-next-ssr#40]
https://github.com/correttojs/graphql-codegen-apollo-next-ssr/blob/dedd8524996f909c9d2db955b05d651e09dc1400/src/visitor.ts#L134

We have two queries, namely `query User {}` and `query UserPage {}`.

However this plugin removes `page` and `query` from any operation name, resulting in duplicating namings `export async function getServerPageUser`

**Comment by correttojs** [comment]
alright, I will add an option to cover your use case

**Comment by correttojs** [comment]
you can set the config `replacePage:false` to cover your case

**Comment by hinsxd** [comment]
Hey thank you for the quick response and update! Definitely will try it 👍
