### ISSUE TITLE
Mutation Behaviour

### ISSUE THREAD

**Issue by ammanvedi** [correttojs/graphql-codegen-apollo-next-ssr#41]
I am wondering if the behaviour when it comes to mutations is correct, for example i am seeing the following be generated

![Screenshot 2020-11-20 at 23 55 28](https://user-images.githubusercontent.com/1761300/99860797-0db03680-2b8c-11eb-8628-40b04ae05848.png)

Since mutations are designed to be deferred should these be ignored somehow ?

**Comment by correttojs** [comment]
Sure, I can exclude the mutations
