### ISSUE TITLE
React 17 support 

### ISSUE THREAD

**Issue by mrtnbroder** [correttojs/graphql-codegen-apollo-next-ssr#52]
https://github.com/correttojs/graphql-codegen-apollo-next-ssr/blob/7f93c87cd783c6fd629f753fad4b025cab5611c8/src/visitor.ts#L94

It would be great if this line could be configured via an option `defaultLibImport` (or maybe you can come up with a better name) where we can configure this line. Some projects may want to use `Preact` or in my case, I don't want any React import at all. (or at least change it to `import * as React from "react"` or since Im using typescript and the only reason react is imported is for types - `import type * as React from "react"`

See the reason for this here on the offical repo: https://github.com/facebook/react/pull/18102

**Comment by correttojs** [comment]
hi, thank you for the feedback
Added the `reactImport` config, the default value is `import type React from 'react'`

**Comment by mrtnbroder** [comment]
Thanks a bunch!
