### ISSUE TITLE
Change `getServerPage<Query>` to return the query instead of the cache/add a new method

### ISSUE THREAD

**Issue by Pikachews** [correttojs/graphql-codegen-apollo-next-ssr#8]
I'm not sure if there's a particular use case for the `getServerPage<Query>` methods returning the entire serialized cache, but I think it would be more valuable to return the result of the query instead so that the return value of the query can be used directly.

i.e. instead of 
```ts
        await apolloClient.query({ ...options, query:Operations.${documentVariableName} });
        const apolloState = apolloClient.cache.extract();
        return {
            props: {
                apolloState,
            },
        };
```

it could return
```ts
        return await apolloClient.query<${operationResultType}>({ ...options, query:Operations.${documentVariableName} });
```

Or if there is a use case for the above, then can a new method for the latter be added? I'd like to use this plugin, but I'd like to use it in `getInitialProps` and also utilize the return value of the query (e.g. checking if the query returned any value), but returning the serialized cache state isn't useful for this purpose.

Thanks!

**Comment by correttojs** [comment]
hi @Pikachews 

sure, that seems reasonable. I'm going to add a new config to return the raw query response

**Comment by Pikachews** [comment]
Thanks for the quick turnaround!
