### ISSUE TITLE
Error: Cannot find name 'Operations'.

### ISSUE THREAD

**Issue by marklawlor** [correttojs/graphql-codegen-apollo-next-ssr#97]
When using a documentMode other than external you will get this error `Cannot find name 'Operations'. ts(2304)`

It appears that this library is [hardcoded](https://github.com/correttojs/graphql-codegen-apollo-next-ssr/blob/f4d1ea8b80a21ff4e58d7021c3a69f8dfb5ef9d6/src/visitor.ts#L159) to for the documents to be external.

I think if the `documentMode` is anything except `external` then `documentVariableName` should not be prefixed with `Operation.`.

**Comment by correttojs** [comment]
hi, could you please share your configuration so I'll be sure to cover your use case? 

This plugin inherits from an existing codegen library, so I need to check if the solution would work with a configurable `Operations` import.

**Comment by marklawlor** [comment]
I am using other graphql-code-generator plugins and do not wish to separate my types across two files.

I would expect this config to work without issue

```
schema:
    - 'https://myschema/graphql'
documents:
    - 'src/**/*.graphql'
generates:
    src/@types/graphql.tsx:
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-react-apollo'
            - graphql-codegen-apollo-next-ssr
```

My work around is to apply this patch

```
diff --git a/node_modules/graphql-codegen-apollo-next-ssr/build/src/visitor.js b/node_modules/graphql-codegen-apollo-next-ssr/build/src/visitor.js
index c23af4f..25f5f68 100644
--- a/node_modules/graphql-codegen-apollo-next-ssr/build/src/visitor.js
+++ b/node_modules/graphql-codegen-apollo-next-ssr/build/src/visitor.js
@@ -82,7 +82,7 @@ class ApolloNextSSRVisitor extends visitor_plugin_common_1.ClientSideBaseVisitor
             ? `export const withPage${pageOperation} = (optionsFunc?: (router: NextRouter)=> QueryHookOptions<${operationResultType}, ${operationVariablesTypes}>) => (WrappedComponent:Page${pageOperation}Comp) : NextPage  => (props) => {
                 const router = useRouter()
                 const options = optionsFunc ? optionsFunc(router) : {};
-                const {data, error } = useQuery(Operations.${documentVariableName}, options)    
+                const {data, error } = useQuery(${documentVariableName}, options)
                 return <WrappedComponent {...props} data={data} error={error} /> ;
 
             }; `
@@ -92,7 +92,7 @@ class ApolloNextSSRVisitor extends visitor_plugin_common_1.ClientSideBaseVisitor
   optionsFunc?: (router: NextRouter)=> QueryHookOptions<${operationResultType}, ${operationVariablesTypes}>) => {
   const router = useRouter();
   const options = optionsFunc ? optionsFunc(router) : {};
-  return useQuery(Operations.${documentVariableName}, options);
+  return useQuery(${documentVariableName}, options);
 };`
             : "";
         const getSSP = `export async function getServerPage${pageOperation}
@@ -103,7 +103,7 @@ class ApolloNextSSRVisitor extends visitor_plugin_common_1.ClientSideBaseVisitor
             ? "const apolloClient = getApolloClient(ctx);"
             : ""}
 
-        const data = await apolloClient.query<${operationResultType}>({ ...options, query:Operations.${documentVariableName} });
+        const data = await apolloClient.query<${operationResultType}>({ ...options, query:${documentVariableName} });
 
         const apolloState = apolloClient.cache.extract();
 
````

Unfortunately I haven't had time to come back and add this as a PR.

**Comment by correttojs** [comment]
Both `typescript-react-apollo` and `graphql-codegen-apollo-next-ssr` extends the `ClientSideBaseVisitor` so the operations would still be duplicated if they are used together in the same generated file.

I made the `Operations.` prefix configurable so the plugin can be used without the `documentMode` `external`

**Comment by marklawlor** [comment]
@correttojs Yep, I'm using [graphql-let](https://github.com/piglovesyou/graphql-let) (a webpack plugin around graphql-code-generator) so that's mostly handled by them. 

Thanks for the fix :+1:  I won't be able to test the update for a little bit but I'll close the issue now
